import turtle # LIBRERÍA PARA UN VIDEOJUEGO.

puntero = turtle.Turtle() # EL PUNTERO ES INCLUIDO DESDE UNA LIBRERÍA.

puntero.speed(1) # VELOCIDAD EN QUE SE EJECUTA EL PUNTERO DEL JUEGO.

# MEDIANTE UN CICLO "for" LOGRAREMOS EJECUTAR ESTAS LÍNEAS DE CÓDIGO.

for i in range(0,4):
    puntero.forward(100) # EL PUNTERO VA HACIA AL FRENTE CON UNA DISTANCIA PREDETERMINADA.
    puntero.left(90) # EL PUNTERO VA HACIA LA IZQUIERDA CON UN ÁNGULO PREDETERMINADO.

turtle.done() # EL PROGRAMA SE EJECUTA CORRECTAMENTE.

